services:
  - type: web
    name: gamestarmd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 gamestarmd:app
    envVars:
      - key: PORT
        value: "5000"